---
title: "Actigraphy Metrics"
author: "Cory Holdom"
format:
  html: default
  gfm: default
editor: visual
echo: true
---

## Overview

Pipeline for the derivation of activity summary metrics for wrist-worn wearables outcomes.

Examples are sourced from the [MotionSense dataset](https://www.kaggle.com/datasets/malekzadeh/motionsense-dataset).

Note: the MotionSense dataset was collected from an iPhone in the users' pockets; estimated metrics are likely not comparable to wrist-worn actigraphy.

```{r Libraries}
#| warning: false
#| output: false

library(tidyverse)
library(gsignal)

filter = dplyr::filter

```

```{r Importing Data}
#| warning: false

Data_raw_sit = rbind(
  readr::read_csv("../Motionsense Data/A_DeviceMotion_data/sit_5/sub_1.csv", 
           col_types = cols_only(`...1` = col_number(),
                                 userAcceleration.x = col_double(), 
                                 userAcceleration.y = col_double(), 
                                 userAcceleration.z = col_double())),
  
  readr::read_csv("../Motionsense Data/A_DeviceMotion_data/sit_13/sub_1.csv", 
                  col_types = cols_only(`...1` = col_number(),
                                        userAcceleration.x = col_double(), 
                                        userAcceleration.y = col_double(), 
                                        userAcceleration.z = col_double()))
)

names(Data_raw_sit) <- c("ts",
                          "userAcceleration_X",
                          "userAcceleration_Y",
                          "userAcceleration_Z")

Data_raw_walk <- readr::read_csv("../Motionsense Data/A_DeviceMotion_data/wlk_7/sub_1.csv",
  col_types = cols_only(`...1` = col_number(),
                        userAcceleration.x = col_double(),
                        userAcceleration.y = col_double(),
                        userAcceleration.z = col_double())
)

names(Data_raw_walk) <- c("ts",
                          "userAcceleration_X",
                          "userAcceleration_Y",
                          "userAcceleration_Z")

Data_raw_walk$ts = Data_raw_walk$ts / 50 # Converting index to a relative time in seconds

Data_raw_walk[,5] = sqrt(Data_raw_walk[,2] ** 2 +
                                           Data_raw_walk[,3] ** 2 +
                                           Data_raw_walk[,4] ** 2)

names(Data_raw_walk)[5] = "userAcceleration_VM"

### --- Jogging --- ###
Data_raw_jog <- readr::read_csv("../Motionsense Data/A_DeviceMotion_data/jog_9/sub_1.csv",
  col_types = cols_only(`...1` = col_number(),
                        userAcceleration.x = col_double(),
                        userAcceleration.y = col_double(),
                        userAcceleration.z = col_double())
)

names(Data_raw_jog) <- c("ts",
                          "userAcceleration_X",
                          "userAcceleration_Y",
                          "userAcceleration_Z")

Data_raw_jog$ts = Data_raw_jog$ts / 50 # Converting index to a relative time in seconds

Data_raw_jog[,5] = sqrt(Data_raw_jog[,2] ** 2 +
                                           Data_raw_jog[,3] ** 2 +
                                           Data_raw_jog[,4] ** 2)

names(Data_raw_jog)[5] = "userAcceleration_VM"

ggplot(Data_raw_walk[1000:1500,], aes(x = ts, y = userAcceleration_VM)) +
  theme_bw() +
  geom_line() +
  labs(title = "Example 10s of walking data", x = "Duration (s)", y = "Vector magnitude of Acceleration (g)")

```

```{r Cleaning and combining accelerometry}

clean_acc = function(raw_signal, filter_order = 6, fs = 50, freq_cutoff = c(0.1, 20)){
  
  # Estimate vector magnitude and direction 
  # Filter data with a band-pass Butterworth filter to smooth motion
  # and remove gravity component
  
  w_cutoff = freq_cutoff / (fs / 2)
  
  butt_filt = gsignal::butter(filter_order, w = freq_cutoff / (fs / 2), type = "pass")
  
  clean_signal = gsignal::filtfilt(butt_filt, raw_signal)
  
  print(gsignal::freqz(butt_filt, fs = fs))
  
  return(clean_signal)
  
}

combine_acc = function(raw_signal, clean = TRUE){
  
  if(clean){
    raw_signal = sapply(raw_signal, clean_acc)
  }
  
  vm = (raw_signal[,1] ** 2 + raw_signal[,2] ** 2 + raw_signal[,3] ** 2) ** 0.5
  
  return(vm)
  
}

```

```{r Cleaned walking data}
Data_clean_walk = data.frame(
  ts = Data_raw_walk$ts,
  sapply(Data_raw_walk[,2:4], clean_acc)
)

Data_clean_walk$userAcceleration_VM = combine_acc(Data_clean_walk[,2:4], clean = F)

ggplot(Data_clean_walk[1000:1500,], aes(x = ts, y = userAcceleration_VM)) +
  theme_bw() +
  geom_line() +
  geom_line(data = Data_raw_walk[1000:1500,], colour = "#662200", alpha = 0.4) +
  labs(title = "Example 10s of (cleaned) walking data", x = "Duration (s)", y = "Acceleration magnitude (g)")
```

```{r Summary of accelerometer characteristics post-filtering}

Data_hist = bind_cols(select(Data_raw_walk, userAcceleration_VM), select(Data_clean_walk, userAcceleration_VM))

names(Data_hist) <- c("Raw", "Cleaned")


Data_hist = pivot_longer(Data_hist, cols = c(Raw, Cleaned))

# Distribution of accelerometer readings
ggplot() +
  theme_bw() +
  geom_histogram(data = Data_hist, aes(x = value, fill = name), position = "identity", alpha = 0.4)

ggplot() +
  theme_bw() +
  geom_density(data = Data_hist, aes(x = value, y = after_stat(density), fill = name), position = "identity", alpha = 0.4)

```

```{r Periodogram}
psd = gsignal::pwelch(x = Data_clean_walk$userAcceleration_VM, fs = 50, window = 1000, detrend = "short-mean")

plot_data = data.frame(
  freq = psd$freq,
  spec = psd$spec
)

peaks = gsignal::findpeaks(data = psd$spec, MinPeakHeight = 0.1)

peak_data = data.frame(
  freq = psd$freq[peaks$loc],
  spec = psd$spec[peaks$loc]
)





ggplot() +
  theme_bw() +
  geom_line(data = plot_data, aes(x = freq, y = spec)) +
  geom_point(data = peak_data, aes(x = freq, y = spec))

```

```{r Functions to estimate activity index}

# Activity Index: the average of the variances over the 3 axes, normalised by
# the device noise. For this measure, I've assumed the recordings during sitting
# are stationary (maybe an overly optimistic assumption, but the exploration of
# the data look alright). The AI is further transformed to original units (g),
# to be on the same scale as the original measure.
# Based on Bai et al., 2016: doi.org/10.1371/journal.pone.0160644

calculate_stationary_variance = function(stationary_signal){
  
  # The variance of the acceleration (in SD units, g^2) is measured by taking
  # the sum of the variance of the three axes at rest
  
  stationary_variance = sd(unlist(stationary_signal[,1], use.names = F)) +
                        sd(unlist(stationary_signal[,2], use.names = F)) +
                        sd(unlist(stationary_signal[,3], use.names = F))
  
  return(stationary_variance) # Sigma_hat^2 in Bai, J. et al., 2016
  
}

aggregate_signal = function(raw_signal, window_length, func = "sd"){
  
  # Group data into "bins" to aggregate over. E.g., if data are recorded at 50Hz
  # and desired output is 1-second summaries, window_length = 50
  
  raw_signal$bin = floor(row_number(raw_signal) / window_length)
  
  # Estimate summary metric (e.g., SD) over each bin
  
  aggregated_signal = aggregate(raw_signal[,2:4],
                  by = raw_signal["bin"],
                  FUN = func)
  
  return(aggregated_signal)
  
}

calculate_activity_index = function(aggregated_signal_variance, stationary_variance = 0, relative_activity_index = FALSE){
  # The sum of the SD in each axis is normalised by the device variance at rest
  # and then divided by 3 to get the average SD over the three axes. The result
  # is transformed with a square root to obtain an activity index on the same
  # units as the original signal.
  # 
  # If relative_activity_index is TRUE, the AI is normalised by the systemic
  # variance of the device
  
  
  
  if(!relative_activity_index){
    
    # print("Estimated AI is not scaled for systemic noise")
    
    mean_of_normalised_variances = (aggregated_signal_variance[2] +
                                    aggregated_signal_variance[3] +
                                    aggregated_signal_variance[4] -
                                    3 * stationary_variance) / 3 
    
    activity_index = max(mean_of_normalised_variances, 0) ^ 0.5
    
    
  }
  
  else{
    
    # print("Estimated AI is scaled for systemic noise")
    
    mean_of_normalised_variances = (aggregated_signal_variance[2] +
                                    aggregated_signal_variance[3] +
                                    aggregated_signal_variance[4] -
                                    3 * stationary_variance) / stationary_variance / 3
    
    activity_index = max(mean_of_normalised_variances, 0) ^ 0.5
 
  }
  
  return(activity_index)
  
}

stat_var = calculate_stationary_variance(Data_raw_sit[,2:4])

aggs = aggregate_signal(Data_raw_walk, window_length = 10, func = sd)

aggs$AI = apply(aggs, MARGIN = 1, FUN = calculate_activity_index, stationary_variance = stat_var, relative_activity_index = F)

plot(aggs$bin[1:100], aggs$AI[1:100], type = "l")

aggs$AI = apply(aggs, MARGIN = 1, FUN = calculate_activity_index, stationary_variance = stat_var, relative_activity_index = T)

plot(aggs$bin[1:100], aggs$AI[1:100], type = "l")

```

```{r Jogging}
stat_var = calculate_stationary_variance(Data_raw_sit[,2:4])

aggs.jog = aggregate_signal(Data_raw_jog, window_length = 10, func = sd)

aggs.jog$AI = apply(aggs.jog, MARGIN = 1, FUN = calculate_activity_index, stationary_variance = stat_var, relative_activity_index = F)

plot(aggs.jog$bin[1:100], aggs.jog$AI[1:100], type = "l")
plot(aggs$bin[1:100], aggs$AI[1:100], type = "l")
```
